/**
 * Database Seeding Script
 * Creates initial data for MAIVÉ platform
 */

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
require('dotenv').config();

const User = require('../models/User');
const Category = require('../models/Category');
const Product = require('../models/Product');
const Settings = require('../models/Settings');
const Lookbook = require('../models/Lookbook');

const seedData = async () => {
  try {
    // Connect to database
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/maive');
    console.log('✅ Successfully connected to MongoDB Atlas');
    
    console.log('📍 Current Database:', mongoose.connection.name);
    // Clear existing data
    await User.deleteMany({});
    await Category.deleteMany({});
    await Product.deleteMany({});
    await Settings.deleteMany({});
    await Lookbook.deleteMany({});
    console.log('🗑️  Cleared existing data');
    
    // Create Super Admin
    const admin = await User.create({
      firstName: 'MAIVÉ',
      lastName: 'Admin',
      email: process.env.ADMIN_EMAIL || 'admin@maive.com',
      password: process.env.ADMIN_PASSWORD || 'Admin123!',
      phone: '+213555555555',
      role: 'superadmin',
      isActive: true
    });
    console.log('👤 Created Super Admin:', admin.email);
    
    // Create Categories with manually generated slugs for safety
    const categoryData = [
      { name: 'Totes', description: 'Spacious and elegant tote bags for everyday use', order: 1, image: 'images/products/img_3548.jpg' },
      { name: 'Mini Bags', description: 'Compact and stylish mini bags for essentials', order: 2, image: 'images/products/img_3580.jpg' },
      { name: 'Pochettes', description: 'Elegant clutches for evening occasions', order: 3, image: 'images/products/img_3560.jpg' },
      { name: 'Épaule', description: 'Shoulder bags for effortless style', order: 4, image: 'images/products/img_3570.jpg' },
      { name: 'Bandoulière', description: 'Crossbody bags for hands-free convenience', order: 5, image: 'images/products/img_3573.jpg' },
      { name: 'Soirée', description: 'Exquisite evening bags for special occasions', order: 6, image: 'images/products/img_3585.jpg' }
    ];

    const categories = [];
    for (const data of categoryData) {
      const cat = new Category(data);
      // Slug will be generated by pre-save hook
      await cat.save();
      categories.push(cat);
    }
    console.log('🏷️  Created', categories.length, 'categories');
    
    // Get category IDs
    const totesCategory = categories.find(c => c.name === 'Totes');
    const miniCategory = categories.find(c => c.name === 'Mini Bags');
    const pochettesCategory = categories.find(c => c.name === 'Pochettes');
    const shoulderCategory = categories.find(c => c.name === 'Épaule');
    const eveningCategory = categories.find(c => c.name === 'Soirée');
    
    // Create Products
    const productData = [
      {
        name: 'Tote MAIVÉ Noir Signature',
        description: 'Le tote signature MAIVÉ en cuir grainé pleine fleur noir. Une pièce intemporelle alliant élégance et praticité.',
        shortDescription: 'Tote signature en cuir grainé pleine fleur',
        basePrice: 42000,
        currency: 'DZD',
        category: totesCategory._id,
        material: 'Cuir grainé pleine fleur',
        dimensions: { length: 35, width: 15, height: 28 },
        status: 'active',
        isFeatured: true,
        isNewArrival: true,
        tags: ['signature', 'classic', 'everyday'],
        variants: [
          {
            name: 'Noir',
            hexCode: '#1a1410',
            images: {
              bagImage: 'images/products/img_3548.jpg',
              modelImage: 'images/products/img_3549.jpg'
            },
            stock: 15,
            sku: 'TOT-NOI-001'
          },
          {
            name: 'Camel',
            hexCode: '#b8986a',
            images: {
              bagImage: 'images/products/img_3552.jpg',
              modelImage: 'images/products/img_3553.jpg'
            },
            stock: 10,
            sku: 'TOT-CAM-001'
          },
          {
            name: 'Crème',
            hexCode: '#f7f3ee',
            images: {
              bagImage: 'images/products/img_3550.jpg',
              modelImage: 'images/products/img_3551.jpg'
            },
            stock: 8,
            sku: 'TOT-CRE-001'
          }
        ],
        createdBy: admin._id
      },
      {
        name: 'Mini Bag MAIVÉ Beige',
        description: 'Le mini bag MAIVÉ en cuir lisse naturel beige. Compact, élégant, et parfait pour toutes les occasions.',
        shortDescription: 'Mini bag en cuir lisse naturel',
        basePrice: 28000,
        currency: 'DZD',
        category: miniCategory._id,
        material: 'Cuir lisse naturel',
        dimensions: { length: 20, width: 8, height: 15 },
        status: 'active',
        isFeatured: true,
        isNewArrival: false,
        tags: ['mini', 'compact', 'versatile'],
        variants: [
          {
            name: 'Beige',
            hexCode: '#c9b99a',
            images: {
              bagImage: 'images/products/img_3580.jpg',
              modelImage: 'images/products/img_3581.jpg'
            },
            stock: 12,
            sku: 'MIN-BEI-001'
          },
          {
            name: 'Noir',
            hexCode: '#1a1410',
            images: {
              bagImage: 'images/products/img_3582.jpg',
              modelImage: 'images/products/img_3583.jpg'
            },
            stock: 10,
            sku: 'MIN-NOI-001'
          }
        ],
        createdBy: admin._id
      },
      {
        name: 'Pochette Soirée Noir',
        description: 'La pochette de soirée MAIVÉ en cuir chic. L\'accessoire parfait pour vos soirées.',
        shortDescription: 'Pochette en cuir chic',
        basePrice: 19000,
        currency: 'DZD',
        category: pochettesCategory._id,
        material: 'Cuir premium',
        dimensions: { length: 25, width: 3, height: 12 },
        status: 'active',
        isFeatured: false,
        isNewArrival: true,
        tags: ['evening', 'chic', 'elegant'],
        variants: [
          {
            name: 'Noir',
            hexCode: '#1a1410',
            images: {
              bagImage: 'images/products/img_3560.jpg',
              modelImage: 'images/products/img_3561.jpg'
            },
            stock: 8,
            sku: 'POC-NOI-001'
          }
        ],
        createdBy: admin._id
      },
      {
        name: 'Sac Épaule Multi MAIVÉ',
        description: 'Le sac porté épaule MAIVÉ polyvalent. Une pièce iconique qui s\'adapte à tous vos styles.',
        shortDescription: 'Sac épaule multi-pochette',
        basePrice: 35000,
        currency: 'DZD',
        category: shoulderCategory._id,
        material: 'Toile et cuir',
        dimensions: { length: 30, width: 12, height: 22 },
        status: 'active',
        isFeatured: true,
        isNewArrival: false,
        tags: ['shoulder', 'classic', 'versatile'],
        variants: [
          {
            name: 'Kaki',
            hexCode: '#4b5320',
            images: {
              bagImage: 'images/products/img_3570.jpg',
              modelImage: 'images/products/img_3571.jpg'
            },
            stock: 10,
            sku: 'EPA-KAK-001'
          },
          {
            name: 'Rose',
            hexCode: '#ffc0cb',
            images: {
              bagImage: 'images/products/img_3573.jpg',
              modelImage: 'images/products/img_3574.jpg'
            },
            stock: 7,
            sku: 'EPA-ROS-001'
          }
        ],
        createdBy: admin._id
      },
      {
        name: 'Minaudière MAIVÉ Or',
        description: 'La minaudière MAIVÉ en satin de soie brodé or. Une pièce d\'exception pour les soirées d\'exception.',
        shortDescription: 'Minaudière en satin de soie brodé',
        basePrice: 31000,
        currency: 'DZD',
        category: eveningCategory._id,
        material: 'Satin de soie brodé',
        dimensions: { length: 18, width: 4, height: 10 },
        status: 'active',
        isFeatured: true,
        isNewArrival: true,
        tags: ['evening', 'luxury', 'exclusive'],
        variants: [
          {
            name: 'Vert',
            hexCode: '#006400',
            images: {
              bagImage: 'images/products/img_3585.jpg',
              modelImage: 'images/products/img_3586.jpg'
            },
            stock: 5,
            sku: 'MIN-VER-001'
          },
          {
            name: 'Bleu',
            hexCode: '#00008b',
            images: {
              bagImage: 'images/products/img_3595.jpg',
              modelImage: 'images/products/img_3594.jpg'
            },
            stock: 4,
            sku: 'MIN-BLE-002'
          }
        ],
        createdBy: admin._id
      }
    ];

    const products = [];
    for (const data of productData) {
      const prod = new Product(data);
      await prod.save();
      products.push(prod);
    }
    console.log('👜 Created', products.length, 'products');
    
    // Update category product counts
    for (const category of categories) {
      const count = await Product.countDocuments({ category: category._id });
      category.productCount = count;
      await category.save();
    }

    // Create Default Settings
    await Settings.create({
      hero: {
        type: 'video',
        url: 'videos/hero-video.mp4',
        title: "L'ESSENCE DE VOTRE RENAISSANCE",
        subtitle: 'Éclat Intemporel, Savoir-faire Algérien'
      },
      announcement: {
        text: 'Livraison gratuite sur toutes les commandes de plus de 50.000 DZD',
        isActive: true
      }
    });
    console.log('⚙️  Created Default Settings');

    // Create Lookbook
    const lookbookProduct = products.find(p => p.name.includes('Tote'));
    await Lookbook.create({
      title: 'L\'Art de Porter MAIVÉ',
      image: 'images/products/img_3548.jpg',
      description: 'Découvrez notre collection signature à travers les rues d\'Alger.',
      hotspots: [
        { x: 45, y: 60, product: lookbookProduct._id }
      ]
    });
    console.log('📖 Created Lookbook');
    
    console.log('\n✅ Seeding completed successfully!');
    console.log('\n📋 Login Credentials:');
    console.log('   Email:', process.env.ADMIN_EMAIL || 'admin@maive.com');
    console.log('   Password:', process.env.ADMIN_PASSWORD || 'Admin123!');
    
    process.exit(0);
  } catch (error) {
    console.error('❌ SEEDING FAILED!');
    console.error('Error Name:', error.name);
    console.error('Error Message:', error.message);
    if (error.message.includes('IP not whitelisted') || error.message.includes('connection timed out')) {
      console.error('👉 ACTION REQUIRED: Check your MongoDB Atlas "Network Access" settings and make sure 0.0.0.0/0 is added.');
    }
    if (error.message.includes('Authentication failed')) {
      console.error('👉 ACTION REQUIRED: Check your password in the MONGODB_URI on Render.');
    }
    process.exit(1);
  }
};

seedData();
